django/website/music/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
import re


app_name = 'music'

urlpatterns = [
	## /music/
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),

    ## /music/id/
    # url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(\d+)/$', views.detail, name='detail'),
    # path('<int:album_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('album/add', views.AlbumCreate.as_view(), name='album-add')

    ## /music/id/favourite/
    # path('<int:album_id>/favourite/', views.favourite, name='favourite'),
]

django/website/website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

django/website/music/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk': self.pk})

	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

django/website/music/views.py
from django.views import generic
from .models import Album



class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'


class AlbumCreate(generic.CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

django/website/music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block body %}
<div class="coutainer-fluid">

	<div class="row">

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'music/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>

				</div>
			</div>
		</div>

	</div>

</div>
{% endblock %}

django/website/music/templates/music/base.html
<!-- <!DOCTYPE html> -->
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title%}Viberr{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>

<body>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">

		<!-- Header -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums	
					</a>
				</li>

				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs	
					</a>
				</li>
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>

			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'music:album-add' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album	
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout	
					</a>
				</li>				
			</ul>

		</div>

	</div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

django/website/music/templates/music/detail-old.html
{% extends 'music/base.html' %}
{% block title%}Album Detail{% endblock %}

{% block body %}
	<img scr="{{ album.album_logo }}">
	<h1>{{ album.album_title }}</h1>
	<h3>{{ album.artist }}</h3>

	<!-- <ul>
		{% for song in album.song_set.all %}
		<li>{{ song.song_title }} - {{ song.file_type }}</li>
		{% endfor %}
	</ul> -->

	{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}

	<form action="{% url 'music:favourite' album.id %}" method="post">
		{% csrf_token %}
		{% for song in album.song_set.all %}
			<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
			<label for="song{{ forloop.counter }}">
				{{ song.song_title }}
				{% if song.is_favorite %}
					<img src="http://i.imgur.com/b9b13Rd.png" />
				{% endif %}
			</label><br>
		{% endfor %}
		<input type="submit" value="Favourite">
	</form>
{% endblock %}

django/website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
	<img scr="{{ album.album_logo }}" style="width: 250px;">

	<h1>{{ album.album_title }}</h1>
	<h2>{{ album.artist }}</h2>

	{% for song in album.song_set.all %}
		{{ song.song_title }}
		{% if song.is_favorite %}
			<img src="http://i.imgur.com/b9b13Rd.png" />
		{% endif %}
		<br>
	{% endfor %}

{% endblock %}

django/website/music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

django/website/music/templates/music/index-old.html
{% extends 'music/base.html' %}


{% block body %}
	{% if all_albums %}
		<h1>Here are all my albums</h1>
		<ul>
			{% for album in all_albums %}
			<!-- <li><a href="/music/{{ album.id }}/">{{ album.album_title }}</a></li> -->
			<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<h3>You don't have any albums</h3>
	{% endif %}
{% endblock %}

django/website/music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}

	<ul>
		{% for album in all_albums %}
		<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
		{% endfor %}
	</ul> 


{% endblock %}