django/album/album/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

django/album/music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.index, name='index'),

    #/music/5
    path('<int:album_id>/', views.detail, name='detail'),
]

django/album/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=1000)
    genre = models.CharField(max_length=50)
    def __str__(self):
        return self.artist + ' - ' + self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=200)
    file_type = models.CharField(max_length=10)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

django/album/music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Album


# Create your views here.
def index(request):
    # return HttpResponse('Hello world!')
    album_all = Album.objects.all()
    context = {
        'album_all': album_all,
    }
    return render(request, 'music/index.html', context)

def detail(request, album_id):
    # try:
    #     album = Album.objects.get(pk=album_id)
    # except Album.DoesNotExist:
    #     raise Http404("This page is not exist")

    album = get_object_or_404(Album, pk=album_id)
    context = {
        'album': album,
    }
    return render(request, 'music/detail.html', context)

django/album/music/templates/music/detail.html
<h1>{{ album.title }}</h1>
<h3>{{ album.artist }}</h3>


<ul>
    {% for song in album.song_set.all %}
    <li>{{song.song_title}} - {{song.file_type}}</li>
    {% endfor %}
</ul>

django/album/music/templates/music/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">
            Home <span class="sr-only">(current)</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

    </ul>

  </div>
</nav>



{% if album_all %}
    <h3>Here are all my albums</h3>
    <ul>
        {% for album in album_all %}
        <li>
            <a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
        </li>
        {% endfor %}
    </ul>

{% else %}
    <h1>You don't have any albums</h1>
{% endif %}